#ifndef __YUNI_PLATFORM_CHECKS_H__
# define __YUNI_PLATFORM_CHECKS_H__

/* This file is generated by CMake */


/* stdio.h */
#define YUNI_HAS_STDIO_H

/* string.h - memcmp, memcmpy... */
#define YUNI_HAS_STRING_H

/* time.h */
#define YUNI_HAS_TIME_H

/* assert.h */
#define YUNI_HAS_ASSERT_H

/* errno.h */
#define YUNI_HAS_ERRNO_H

/* cstddef */
#define YUNI_HAS_CSTDDEF

/* dirent.h */
#define YUNI_HAS_DIRENT_H

/* stdlib.h */
#define YUNI_HAS_STDLIB_H

/* unistd.h */
#define YUNI_HAS_UNISTD_H

/* fcntl.h */
#define YUNI_HAS_FCNTL_H

/* cstdlib */
/* #undef YUNI_HAS_CSTDLIB */

/* stdarg.h */
#define YUNI_HAS_STDARG_H

/* va_copy */
#define YUNI_HAS_VA_COPY

/* sys/sendfile.h */
#define YUNI_HAS_SYS_SENDFILE_H




/* sys/types.h */
#define YUNI_HAS_SYS_TYPES_H

/* winsock2.h */
/* #undef YUNI_HAS_WINSOCK_2 */

/* ShellApi.h */
/* #undef YUNI_HAS_SHELLAPI_H */

/* climits */
#define YUNI_HAS_CLIMITS

/* vector */
#define YUNI_HAS_VECTOR

/* list */
#define YUNI_HAS_LIST

/* map */
#define YUNI_HAS_MAP

/* algorithm */
#define YUNI_HAS_ALGORITHM

/* cassert */
#define YUNI_HAS_CASSERT






/* C++0x support by gcc (-std=c++0x) */
#define YUNI_HAS_GCC_CPP0X_SUPPORT

/* long types - different from int */
/* #undef YUNI_HAS_LONG */

/* int64_t, from stdint.h */
#define YUNI_HAS_INT64_T

/* int128_t, from stdint.h */
/* #undef YUNI_HAS_INT128_T */

/* uint */
#define YUNI_HAS_UINT

/* ssize_t */
#define YUNI_HAS_SSIZE_T

/* C++0x support: nullptr (GCC: only >= 4.6 with -std=gnu++0x, VS: only >= 10) */
/* #undef YUNI_HAS_NULLPTR */

/* gcc __sync_add_and_fetch */
#define YUNI_HAS_SYNC_ADD_AND_FETCH



#endif /* __YUNI_PLATFORM_CHECKS_H__ */
